In [1]:
# np.sort
# -> Return a sorted copy of an array 


In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([28, 11, 26, 60, 62, 89, 86, 80, 91, 22, 17, 80, 95, 41, 90],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 26, 65, 87],
       [11, 82, 10, 84],
       [11, 91, 96, 38],
       [28, 72, 54, 43],
       [48, 27, 88, 28],
       [21, 64, 42, 21]], dtype=int32)

In [5]:
# sorted array 
np.sort(a)

array([11, 17, 22, 26, 28, 41, 60, 62, 80, 80, 86, 89, 90, 91, 95],
      dtype=int32)

In [8]:
np.sort(b) # row wise sorting

array([[10, 26, 65, 87],
       [10, 11, 82, 84],
       [11, 38, 91, 96],
       [28, 43, 54, 72],
       [27, 28, 48, 88],
       [21, 21, 42, 64]], dtype=int32)

In [7]:
# numpy.sort(a, axis=-1, kind=None, order=None)
# axis : int, optional
# Axis along which to sort. Default is -1, which means sort along the last axis.
# kind : {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional
# Sorting algorithm. Default is ‘quicksort’.
# order : str or list of str, optional


In [10]:
# coulmn wise sorting
np.sort(b, axis=0)
# axis = 0 means column wise sorting
# axis = 1 means row wise sorting


array([[10, 26, 10, 21],
       [11, 27, 42, 28],
       [11, 64, 54, 38],
       [21, 72, 65, 43],
       [28, 82, 88, 84],
       [48, 91, 96, 87]], dtype=int32)

In [11]:
# decreasing order sorting
np.sort(a)[::-1]

array([95, 91, 90, 89, 86, 80, 80, 62, 60, 41, 28, 26, 22, 17, 11],
      dtype=int32)