In [1]:
# np.sort
# -> Return a sorted copy of an array 


In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([28, 11, 26, 60, 62, 89, 86, 80, 91, 22, 17, 80, 95, 41, 90],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 26, 65, 87],
       [11, 82, 10, 84],
       [11, 91, 96, 38],
       [28, 72, 54, 43],
       [48, 27, 88, 28],
       [21, 64, 42, 21]], dtype=int32)

In [5]:
# sorted array 
np.sort(a)

array([11, 17, 22, 26, 28, 41, 60, 62, 80, 80, 86, 89, 90, 91, 95],
      dtype=int32)

In [8]:
np.sort(b) # row wise sorting

array([[10, 26, 65, 87],
       [10, 11, 82, 84],
       [11, 38, 91, 96],
       [28, 43, 54, 72],
       [27, 28, 48, 88],
       [21, 21, 42, 64]], dtype=int32)

In [7]:
# numpy.sort(a, axis=-1, kind=None, order=None)
# axis : int, optional
# Axis along which to sort. Default is -1, which means sort along the last axis.
# kind : {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional
# Sorting algorithm. Default is ‘quicksort’.
# order : str or list of str, optional


In [10]:
# coulmn wise sorting
np.sort(b, axis=0)
# axis = 0 means column wise sorting
# axis = 1 means row wise sorting


array([[10, 26, 10, 21],
       [11, 27, 42, 28],
       [11, 64, 54, 38],
       [21, 72, 65, 43],
       [28, 82, 88, 84],
       [48, 91, 96, 87]], dtype=int32)

In [11]:
# decreasing order sorting
np.sort(a)[::-1]

array([95, 91, 90, 89, 86, 80, 80, 62, 60, 41, 28, 26, 22, 17, 11],
      dtype=int32)

In [12]:
## APPEND -> np.append(arr, values, axis=None)
# Append values to the end of an array.
a = np.random.randint(1,100,15)
a

array([62, 64,  5, 10, 27, 91, 17, 62, 57, 46, 73, 92, 28, 24, 76],
      dtype=int32)

In [14]:
# add 200 at the end of array a
np.append(a,200)

array([ 62,  64,   5,  10,  27,  91,  17,  62,  57,  46,  73,  92,  28,
        24,  76, 200])

In [15]:
# append ua=sing 2d array 
b

array([[10, 26, 65, 87],
       [11, 82, 10, 84],
       [11, 91, 96, 38],
       [28, 72, 54, 43],
       [48, 27, 88, 28],
       [21, 64, 42, 21]], dtype=int32)

In [16]:
# add one columna at end with 1s
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[10., 26., 65., 87.,  1.],
       [11., 82., 10., 84.,  1.],
       [11., 91., 96., 38.,  1.],
       [28., 72., 54., 43.,  1.],
       [48., 27., 88., 28.,  1.],
       [21., 64., 42., 21.,  1.]])

In [20]:
## np.concatenate((a1, a2, ...), axis=0, out=None)
# Join a sequence of arrays along an existing axis.
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)    
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [21]:
# concatinate c and d row wise
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
# column wise concatination
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [23]:
## np.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
# Find the unique elements of an array.

# with the help of unique we can find the unique elements of an array

e = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
## np.expand_dims(a, axis)
# Expand the shape of an array.
# Insert a new axis that will appear at the axis position in the expanded array shape.
# axis : int
# Position in the expanded axes where the new axis is placed.


In [25]:
a

array([28, 14, 67, 84, 15, 14, 11, 37, 93, 14, 87, 58, 73, 25, 90],
      dtype=int32)

In [27]:
# convert this 1d array into 2d array
np.expand_dims(a, axis=0).shape

(1, 15)

In [28]:
np.expand_dims(a, axis=1)

array([[28],
       [14],
       [67],
       [84],
       [15],
       [14],
       [11],
       [37],
       [93],
       [14],
       [87],
       [58],
       [73],
       [25],
       [90]], dtype=int32)

In [29]:
# usecase of this -> in ml we need to convert 1d array into 2d array
# for that we use expand_dims


In [30]:
# np.where(condition[, x, y])
# Return elements chosen from x or y depending on condition.
# condition : array_like, bool
# Where True, yield x, otherwise yield y.
# x, y : array_like
# Values from which to choose. x, y and condition need to be broadcastable to some shape.


In [31]:
a

array([28, 14, 67, 84, 15, 14, 11, 37, 93, 14, 87, 58, 73, 25, 90],
      dtype=int32)

In [33]:
# find all indices where value is greater than 50
np.where(a>50) # gives indices

(array([ 2,  3,  8, 10, 11, 12, 14]),)

In [34]:
# replace all values greater than 50 with 100
np.where(a>50,100,a)

array([ 28,  14, 100, 100,  15,  14,  11,  37, 100,  14, 100, 100, 100,
        25, 100], dtype=int32)

In [35]:
## np.argmax(a, axis=None, out=None)
# Returns the indices of the maximum values along an axis.
# axis : int, optional
# By default, the index is into the flattened array, otherwise along the specified axis.
# out : array, optional
# If provided, the result will be inserted into this array. It should be of the appropriate shape and dtype.

In [36]:
a

array([28, 14, 67, 84, 15, 14, 11, 37, 93, 14, 87, 58, 73, 25, 90],
      dtype=int32)

In [37]:
# in a where is the largest element 
np.argmax(a)

np.int64(8)

In [38]:
b

array([[10, 26, 65, 87],
       [11, 82, 10, 84],
       [11, 91, 96, 38],
       [28, 72, 54, 43],
       [48, 27, 88, 28],
       [21, 64, 42, 21]], dtype=int32)

In [39]:
np.argmax(b,axis=0) # column wise

array([4, 2, 2, 0])

In [40]:
# row wise
np.argmax(b,axis=1)

array([3, 3, 2, 1, 2, 1])

In [41]:
## np.argmin(a, axis=None, out=None)
# Returns the indices of the minimum values along an axis.
# axis : int, optional
# By default, the index is into the flattened array, otherwise along the specified axis.
# out : array, optional
# If provided, the result will be inserted into this array. It should be of the appropriate shape and dtype.


In [42]:
np.argmin(a)

np.int64(6)

### np.cumsum

- numpy.cumsum() function is used when we want to compute the cumulative sum if aray elements over a given axis

In [43]:
# cumulative sum -> np.cumsum(a, axis=None, dtype=None, out=None)
# Return the cumulative sum of the elements along a given axis.
# what is cumulative sum -> [1,2,3,4,5] -> [1,3,6,10,15]
# means -> 1, 1+2, 1+2+3, 1+2+3+4, 1+2+3+4+5



In [44]:
a

array([28, 14, 67, 84, 15, 14, 11, 37, 93, 14, 87, 58, 73, 25, 90],
      dtype=int32)

In [45]:
np.cumsum(a)

array([ 28,  42, 109, 193, 208, 222, 233, 270, 363, 377, 464, 522, 595,
       620, 710])

### np.percentile

- numpy.percentile() function used to compute the nth percentile of the given data(array elements) along the spefied axis.

In [51]:
# np.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
# Compute the q-th percentile of the data along the specified axis.
# q : float in range of [0,100] (or sequence of floats)
# Percentile to compute, which must be between 0 and 100 inclusive.
# formula -> (p/100) * (n+1) -> p = 25, n = 10 -> (25/100) * (10+1) = 2.75
# 2.75th index value is 2nd index value


In [47]:
a

array([28, 14, 67, 84, 15, 14, 11, 37, 93, 14, 87, 58, 73, 25, 90],
      dtype=int32)

In [48]:
# find 100th percentile 
np.percentile(a,100)

np.float64(93.0)

In [49]:
# 0th percentile 
np.percentile(a,0)

np.float64(11.0)

In [50]:
# 50th percentile
np.percentile(a,50)

np.float64(37.0)