### Numpy array vs Python lists

In [3]:
# numpy array is much faster than python list 
# speed and time test for python list 
a = [i for i in range(1000000)]
b = [i for i in range(1000000,20000000)]

c =[]
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print("time taken for python list is ", time.time()-start)

time taken for python list is  1.4739022254943848


In [5]:
## same thing with numpy array
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print("time taken for numpy array is ", time.time()-start)


time taken for numpy array is  0.2651960849761963


In [6]:
# total time gap 
1.4739022254943848 /  0.2651960849761963

5.557782746403215

In [ ]:
# memory occupied by numpy array is less than python list
a = [i for i in range(1000000)]

import sys
print(sys.getsizeof(a)) # bytes of memory 

8448728


In [ ]:
# memory occupization by numpy array
a = np.arange(1000000 , dtype = np.int32)
print(a.nbytes) # bytes of memory

# memory for int 32 


4000000


### Advance Indexing

In [11]:
# Normal Indexing and Slicing 

a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
# find element 5
a[1,1]

np.int64(5)

In [13]:
# slicing -> find 5,6 and 9,10
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [16]:
## Fancy Indexing -> passing list of indices

a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
# find 1,3 and 4 th row
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
# 1,2,3,cllumn
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [21]:
# 1,3,4,6 row
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])