### Numpy array vs Python lists

In [3]:
# numpy array is much faster than python list 
# speed and time test for python list 
a = [i for i in range(1000000)]
b = [i for i in range(1000000,20000000)]

c =[]
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print("time taken for python list is ", time.time()-start)

time taken for python list is  1.4739022254943848


In [3]:
## same thing with numpy array
import numpy as np
import time
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print("time taken for numpy array is ", time.time()-start)


time taken for numpy array is  0.11795568466186523


In [6]:
# total time gap 
1.4739022254943848 /  0.2651960849761963

5.557782746403215

In [ ]:
# memory occupied by numpy array is less than python list
a = [i for i in range(1000000)]

import sys
print(sys.getsizeof(a)) # bytes of memory 

8448728


In [ ]:
# memory occupization by numpy array
a = np.arange(1000000 , dtype = np.int32)
print(a.nbytes) # bytes of memory

# memory for int 32 


4000000


### Advance Indexing

In [11]:
# Normal Indexing and Slicing 

a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
# find element 5
a[1,1]

np.int64(5)

In [13]:
# slicing -> find 5,6 and 9,10
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [16]:
## Fancy Indexing -> passing list of indices

a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
# find 1,3 and 4 th row
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
# 1,2,3,cllumn
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [21]:
# 1,3,4,6 row
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [27]:
## BOOLEAN INDEXING 

a = np.random.randint(1,100,24).reshape(6,4)
a

array([[91, 77, 64, 38],
       [13, 21, 85, 39],
       [63, 30, 63, 37],
       [20,  8,  9, 29],
       [79,  6, 16, 19],
       [74, 36, 94, 67]], dtype=int32)

In [28]:
# find those number greater than 50
a > 50

array([[ True,  True,  True, False],
       [False, False,  True, False],
       [ True, False,  True, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False,  True,  True]])

In [31]:
a[a>50]

array([91, 77, 64, 85, 63, 63, 79, 74, 94, 67], dtype=int32)

In [32]:
# find even numbers
a % 2 == 0

array([[False, False,  True,  True],
       [False, False, False, False],
       [False,  True, False, False],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [ True,  True,  True, False]])

In [33]:
a[a % 2 == 0]

array([64, 38, 30, 20,  8,  6, 16, 74, 36, 94], dtype=int32)

In [35]:
# find number greater than 50 and even 
(a>50) & (a%2 == 0) # use bit wise operator for boolena operators

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False]])

In [36]:
a[(a>50) & (a%2 == 0)]

array([64, 74, 94], dtype=int32)

## Broadcasting

The term **broadcasting** describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is **"broadcast"** across the larger array so that they have compatible shapes.



In [38]:
# same shape 
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)    
print(a)
print(b)

print('Item wise addition',a+b)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
Item wise addition [[ 6  8 10]
 [12 14 16]]


In [39]:
# different shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)    
print(a)
print(b)

print('Item wise addition',a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
Item wise addition [[0 2 4]
 [3 5 7]]


### Mathematical Function

In [ ]:
import numpy as np

# sigmoid function -> 1/(1+e^-x)
# defination -> sigmoid function is a mathematical function that maps any real value to a value between 0 and 1.
# It is non-linear function used in machine learning for binary classification problem.
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Example usage

arr = np.array([-2, -1, 0, 1, 2])
sigmoid_arr = sigmoid(arr)
print(sigmoid_arr)

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [7]:
# mean square error -> 1/n * sum(y-y^)^2
# defination -> Mean square error is the average of the square of the errors. The larger the number the larger the error.
# It is used to measure the difference between the values predicted by the model and the actual values.

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

print('Actual',actual)
print('Predicted',predicted)


Actual [18  7 37  7 46 41 34  6  2  8 36 35 25  7 47 10 16 29 29 12 21 45 20 45
 18]
Predicted [40 30 10 36 44 29 33 10 46 35 13 16 15 41 26 26 11 34 14  5 37 34 19 10
  9]


In [9]:
# MSE(Mean Square Error)
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)

print('Mean Square Error',mse(actual,predicted))

Mean Square Error 410.56
