In [1]:
## -> Numpy is the fundamental package for scientific computing with Python.
# -> It contains among other things a powerful N-dimensional array object,

In [2]:

# example for nupy array creation 

import numpy as np

In [ ]:
# also can create using np.array() function
a = np.array([1,2,3,4,5])
print(a)
# this is a 1D array and can be called as vector


[1 2 3 4 5]


In [ ]:
# creating 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)
# can be called as matrix

[[1 2 3]
 [4 5 6]]


In [6]:
# tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# create array with data types

# float data type

np.array([0,1,0], dtype=float)c

array([0., 1., 0.])

In [8]:
# bool data type
np.array([0,1,0], dtype=bool)

array([False,  True, False])

In [9]:
# complex data type
np.array([0,1,0], dtype=complex)

array([0.+0.j, 1.+0.j, 0.+0.j])

In [10]:
# create npraay in range -> arange() function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# with reshape -> to convert given array into given shape
np.arange(1,11).reshape(2,5) # .reshape(row, column)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:

# np.ones() -> create array with all elements as 1
np.ones((3,4))
# use of creating this ? -> In neural network, we can use this to create bias

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# np.zeros() -> create array with all elements as 0
np.zeros((3,4))
# use of creating this ? -> In neural network, we can use this to create weights

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# create a random array
np.random.random((2,3)) 

array([[0.72452686, 0.5893929 , 0.02145806],
       [0.27113682, 0.43779755, 0.93969283]])

In [24]:
# np.lespace() -> create array with given range and number of elements
np.linspace(1,5,10) # (start, end, number of elements)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
# np.identity() -> create identity matrix
np.identity(3) # 3x3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])