In [1]:
## -> Numpy is the fundamental package for scientific computing with Python.
# -> It contains among other things a powerful N-dimensional array object,

In [2]:

# example for nupy array creation 

import numpy as np

In [ ]:
# also can create using np.array() function
a = np.array([1,2,3,4,5])
print(a)
# this is a 1D array and can be called as vector


[1 2 3 4 5]


In [ ]:
# creating 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)
# can be called as matrix

[[1 2 3]
 [4 5 6]]


In [6]:
# tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# create array with data types

# float data type

np.array([0,1,0], dtype=float)c

array([0., 1., 0.])

In [8]:
# bool data type
np.array([0,1,0], dtype=bool)

array([False,  True, False])

In [9]:
# complex data type
np.array([0,1,0], dtype=complex)

array([0.+0.j, 1.+0.j, 0.+0.j])

In [10]:
# create npraay in range -> arange() function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# with reshape -> to convert given array into given shape
np.arange(1,11).reshape(2,5) # .reshape(row, column)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:

# np.ones() -> create array with all elements as 1
np.ones((3,4))
# use of creating this ? -> In neural network, we can use this to create bias

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# np.zeros() -> create array with all elements as 0
np.zeros((3,4))
# use of creating this ? -> In neural network, we can use this to create weights

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# create a random array
np.random.random((2,3)) 

array([[0.72452686, 0.5893929 , 0.02145806],
       [0.27113682, 0.43779755, 0.93969283]])

In [24]:
# np.lespace() -> create array with given range and number of elements
np.linspace(1,5,10) # (start, end, number of elements)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
# np.identity() -> create identity matrix
np.identity(3) # 3x3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# by default when we create a numpy array is will be float64
# we can change the data type using dtype parameter

### Array Attributes 

In [27]:
# Every numpy array is the object of numpy class
# Every numpy array has 2 parts -> 1. Data 2. Metadata
# Data -> actual data of the array
# Metadata -> information about the data like shape, data type, etc.


In [33]:
a1 = np.arange(10) # vector
a2 = np.arange(12,dtype=float).reshape(3,4) # matrix
a3 = np.arange(24,dtype=float).reshape(2,3,4) # tensor

print('This is a1 :->',a1)
print('This is a2 :->',a2)
print('This is a3 :->',a3)

This is a1 :-> [0 1 2 3 4 5 6 7 8 9]
This is a2 :-> [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
This is a3 :-> [[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [34]:
# ndim -> to get the dimension of the array
a1.ndim

1

In [35]:
a2.ndim

2

In [36]:
a3.ndim

3

In [37]:
# shape -> to get the shape of the array and it will tell the number of rows and columns

a1.shape

(10,)

In [38]:
a2.shape

(3, 4)

In [42]:
print(a3.shape)
a3 # means there are 2 matrix with 3 rows and 4 columns

(2, 3, 4)


array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [44]:
# size -> to get the total number of elements in the array

a3.size

24

In [45]:
a2.size

12

In [46]:
a1.size

10

In [47]:
# itemsize -> to get the size of each element in the array
a3.itemsize

8

In [49]:
a3.itemsize

8

In [50]:
# dtype -> to get the data type of the array
a1.dtype

dtype('int64')

### Changing Datatype

In [ ]:
# astype() -> to change the data type of the array
a3.dtype # initial data tye is float64

dtype('float64')

In [54]:
# to change use -> astype()
a3.astype(np.int32) # changed to int32
# benefits of changing data type -> memory optimization


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)

### Array Operations

In [57]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(15,30).reshape(5,3)
a2

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [58]:
# scalar operation 

# addition
a1 + 5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
# multiplication
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
# relational operator -> return boolean value

a2>5

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [64]:
# vector operations -> element wise operations

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)
a1 + a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [66]:
# relational operator -> element wise operations
a1 == a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### Array Functions

In [4]:
# array functions
a1 = np.random.random((3,4))
print(a1)
a1 = np.round(a1*100)
print(a1)

[[0.76184738 0.54051039 0.84709592 0.20351502]
 [0.42476921 0.96280919 0.05753617 0.42275313]
 [0.26280294 0.59956323 0.89148681 0.72259839]]
[[76. 54. 85. 20.]
 [42. 96.  6. 42.]
 [26. 60. 89. 72.]]


In [ ]:
# array functions
# max
# min
# sum
# prod

In [7]:
# max
np.max(a1)

np.float64(96.0)

In [8]:
# min
np.min(a1)  

np.float64(6.0)

In [9]:
# sum
np.sum(a1)

np.float64(668.0)

In [10]:
# prod
np.prod(a1)

np.float64(7.08638003108905e+19)

In [13]:
# # to find min of every matrix

# 0-> column wise
# 1-> row wise
np.min(a1, axis=0)
print(np.min(a1, axis=1))
print(np.max(a1, axis=1))

[20.  6. 26.]
[85. 96. 89.]


In [14]:
# mean/median/std/var

In [15]:
np.mean(a1)

np.float64(55.666666666666664)

In [16]:
# median
np.median(a1)

np.float64(57.0)

In [17]:
# std
np.std(a1)

np.float64(27.827843770024455)

In [18]:
# var
np.var(a1)

np.float64(774.3888888888888)

In [21]:
## dot product 
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
print(a1)
print(a2)
np.dot(a1,a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [23]:
# log and exponent 
# log
np.log(a1)


C:\Users\harsh\AppData\Local\Temp\ipykernel_10796\3391467709.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [24]:
# exponent
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [29]:
# round/floor/ceil

# round
a1 = np.random.random((3,4))
print(a1)
np.round(a1,2)

[[0.34085962 0.64446921 0.65239988 0.07990917]
 [0.77827262 0.41593163 0.83422264 0.19067874]
 [0.38193521 0.68649043 0.43181909 0.58391256]]


array([[0.34, 0.64, 0.65, 0.08],
       [0.78, 0.42, 0.83, 0.19],
       [0.38, 0.69, 0.43, 0.58]])

In [31]:
# floor
# floor -> round down the value to the nearest integer value in the array to the nearest integer value
np.floor(np.random.random((3,4))*10)

array([[4., 2., 1., 5.],
       [7., 5., 5., 7.],
       [8., 8., 6., 4.]])

In [32]:
# ceil -> round up the value to the nearest integer value in the array to the nearest integer value
np.ceil(np.random.random((3,4))*10)

array([[ 3.,  9., 10.,  4.],
       [ 8.,  5.,  5.,  5.],
       [ 9.,  5.,  9.,  5.]])

### Indexing and Slicing 

In [33]:
# to fetch item from the array we can use index
# there are 2 types of indexing -> 1. Positive indexing 2. Negative indexing

a1 = np.arange(12).reshape(3,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
# find the element at 2nd row and 3rd column
a1[1,2]

np.int64(6)

In [36]:
# find last item of the array
a1[-1,-1]

np.int64(11)

In [38]:
# 3d array
a1 = np.arange(24).reshape(2,3,4)
print(a1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
# find elemnt 18
a1[1,1,2]

np.int64(18)

In [40]:
# find 20 
a1[1,2,0]

np.int64(20)

In [41]:
## Slicing -> to get the subset of the array or multiple elements from the array

a1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [43]:
# first create a 1d array
a1 = np.arange(12)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
# fetch first 5 elements
a1[:5]

array([0, 1, 2, 3, 4])

In [46]:
# fetch from 3-10
a1[3:11]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# in 2d array 
a1 = np.arange(12).reshape(3,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [61]:
# find 5 and 7
a1[1,1:3]

array([5, 6])

In [57]:
# find 4 and 7
a1[1,::3]

array([4, 7])

In [56]:
# find 1,3 and 9,11
a1[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [48]:
# find first row
a1[0]

array([0, 1, 2, 3])

In [ ]:
# 3rd column
a1[:,2]  # -> [row, column]

array([ 2,  6, 10])

In [ ]:
# find 5 and 6 and 9 and 10
a1[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [54]:
# find 1 and 2 and 5 and 6
a1[:2,1:3]


array([[1, 2],
       [5, 6]])